### ISSUE TITLE
Issue with redefines with picture clause (which is not group)

### ISSUE THREAD

**Issue by Nandakishore43** [rbheemana/Cobol-to-Hive#44] opened 2017-12-18 15:24 UTC
I see the code is not handling redefines with self picture clause, Can you guide me , So that I can enhacne the code and give it 

EX: 
30 TOTAL-INT           REDEFINES           TOTAL-FEE         PIC S9(12)V9(05) COMP-3.

Please help asap , its really need for us

**Comment by nayven3** [comment] 2017-12-27 11:00
CREATE TABLE MF_table
 ROW FORMAT SERDE 'com.savy3.hadoop.hive.serde3.cobol.CobolSerDe'
 STORED AS
 INPUTFORMAT 'org.apache.hadoop.mapred.FixedLengthInputFormat'
 OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat'
 TBLPROPERTIES ('cobol.layout.literal'='01 MF-MINI-REC. 30  TOTAL-FEE PIC 9(12)V9(05) COMP-3. 30 TOTAL-INT REDEFINES TOTAL-FEE PIC S9(12)V9(05) COMP-3.');

hive> desc mf_table;
OK
total_fee               decimal(18,5)           30 TOTAL-FEE PIC 9(12)V9(05) COMP-3|0|9
total_int               decimal(18,5)           30 TOTAL-INT REDEFINES TOTAL-FEE PIC S9(12)V9(05) COMP-3.|0|9

It works as expected. Can you please share your copybook so that we can reproduce the issue and suggests you.

**Comment by Nandakishore43** [comment] 2017-12-28 10:22
Hi nayven3 <Thanks for looking in to this. I had attached sample copybook, I see issue is when self redefines inside Occurs


[Sample Copybook.txt](https://github.com/rbheemana/Cobol-to-Hive/files/1591017/Sample.Copybook.txt)

**Comment by nayven3** [comment] 2018-01-12 09:40
It seems to be Duplicate name creating inside the Occurs. if you downloaded the code then please 
replace the below code 

if(occurs>1) {                              							// before changes : if(occurs>1) Venka: b4 changes
							hiveColumnNames.add(cf.getName()+"_oc"+(occurs-count+1));		// Venka: Added   
							recurssive_cnt = occurs-count+1;								// Venka: Added   
					}else if(occurs == 1 && recurssive_cnt > 0) {  			                // before changes : if(occurs>1) Venka: b4 changes
							hiveColumnNames.add(cf.getName()+"_oc"+(recurssive_cnt));   	// Venka: Added
					}else {                                                         		// Venka: Added
						
Then you can create table as below. 
``````````````````````````````````````````````````````````````
ws_bill_event_ty_cd_oc1 varchar(4)              30 ws-BILL-EVENT-TY-CD PIC X(04)|0|4
ws_bill_rqst_cd_oc1     varchar(1)              30 ws-BILL-RQST-CD PIC X(01)|4|1
ws_fee_exempt_id_oc1    varchar(1)              30 ws-FEE-EXEMPT-ID PIC X(01)|5|1
ws_fee_exempt_rsn_cd_oc1        varchar(4)              30 ws-FEE-EXEMPT-RSN-CD PIC X(04)|6|4
ws_rule_fee_cd_oc1      varchar(4)              30 ws-RULE-FEE-CD PIC X(04)|10|4
ws_fee_calc_rcl_cd_oc1  varchar(3)              30 ws-FEE-CALC-RCL-CD PIC X(03)|14|3
ws_total_fee_oc1        decimal(18,2)           30 ws-TOTAL-FEE PIC S9(15)V99 COMP-3|17|9
ws_total_int_oc1        decimal(18,5)           30 ws-TOTAL-INT REDEFINES ws-TOTAL-FEE PIC S9(12)V9(05) COMP-3|17|9
ws_pers_fee_oc1         decimal(18,2)           30 ws-PERS-FEE PIC S9(15)V99 COMP-3|26|9
ws_fund_based_acct_chg_oc1      decimal(18,2)           30 ws-FUND-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|26|9
ws_ibd_based_acct_chg_oc1       decimal(18,2)           30 ws-IBD-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|26|9
ws_pers_int_oc1         decimal(18,5)           30 ws-PERS-INT REDEFINES ws-PERS-FEE PIC S9(12)V9(05) COMP-3|26|9
ws_ibd_mark_up_fee_oc1  decimal(18,2)           30 ws-IBD-MARK-UP-FEE PIC S9(15)V99 COMP-3|35|9
ws_ibd_mark_up_int_oc1  decimal(18,5)           30 ws-IBD-MARK-UP-INT REDEFINES ws-IBD-MARK-UP-FEE PIC S9(12)V9(05) COMP-3|35|9
ws_contract_schd_id_oc1 varchar(12)             30 ws-CONTRACT-SCHD-ID PIC X(12)|44|12
ws_ebs_req_ent_id_oc1   varchar(12)             30 ws-EBS-REQ-ENT-ID PIC X(12)|56|12
ws_bill_rule_set_id_oc1 varchar(12)             30 ws-BILL-RULE-SET-ID PIC X(12)|68|12
ws_tran_bundle_id_oc1   varchar(12)             30 ws-TRAN-BUNDLE-ID PIC X(12)|80|12
ws_fxcpt_rule_set_id_oc1        varchar(12)             30 ws-FXCPT-RULE-SET-ID REDEFINES ws-TRAN-BUNDLE-ID PIC X(12)|80|12
ws_bundle_ind_oc1       varchar(1)              30 ws-BUNDLE-IND PIC X(01).|92|1
ws_bill_event_ty_cd_oc2 varchar(4)              30 ws-BILL-EVENT-TY-CD PIC X(04)|93|4
ws_bill_rqst_cd_oc2     varchar(1)              30 ws-BILL-RQST-CD PIC X(01)|97|1
ws_fee_exempt_id_oc2    varchar(1)              30 ws-FEE-EXEMPT-ID PIC X(01)|98|1
ws_fee_exempt_rsn_cd_oc2        varchar(4)              30 ws-FEE-EXEMPT-RSN-CD PIC X(04)|99|4
ws_rule_fee_cd_oc2      varchar(4)              30 ws-RULE-FEE-CD PIC X(04)|103|4
ws_fee_calc_rcl_cd_oc2  varchar(3)              30 ws-FEE-CALC-RCL-CD PIC X(03)|107|3
ws_total_fee_oc2        decimal(18,2)           30 ws-TOTAL-FEE PIC S9(15)V99 COMP-3|110|9
ws_total_int_oc2        decimal(18,5)           30 ws-TOTAL-INT REDEFINES ws-TOTAL-FEE PIC S9(12)V9(05) COMP-3|110|9
ws_pers_fee_oc2         decimal(18,2)           30 ws-PERS-FEE PIC S9(15)V99 COMP-3|119|9
ws_fund_based_acct_chg_oc2      decimal(18,2)           30 ws-FUND-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|119|9
ws_ibd_based_acct_chg_oc2       decimal(18,2)           30 ws-IBD-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|119|9
ws_pers_int_oc2         decimal(18,5)           30 ws-PERS-INT REDEFINES ws-PERS-FEE PIC S9(12)V9(05) COMP-3|119|9
ws_ibd_mark_up_fee_oc2  decimal(18,2)           30 ws-IBD-MARK-UP-FEE PIC S9(15)V99 COMP-3|128|9
ws_ibd_mark_up_int_oc2  decimal(18,5)           30 ws-IBD-MARK-UP-INT REDEFINES ws-IBD-MARK-UP-FEE PIC S9(12)V9(05) COMP-3|128|9
ws_contract_schd_id_oc2 varchar(12)             30 ws-CONTRACT-SCHD-ID PIC X(12)|137|12
ws_ebs_req_ent_id_oc2   varchar(12)             30 ws-EBS-REQ-ENT-ID PIC X(12)|149|12
ws_bill_rule_set_id_oc2 varchar(12)             30 ws-BILL-RULE-SET-ID PIC X(12)|161|12
ws_tran_bundle_id_oc2   varchar(12)             30 ws-TRAN-BUNDLE-ID PIC X(12)|173|12
ws_fxcpt_rule_set_id_oc2        varchar(12)             30 ws-FXCPT-RULE-SET-ID REDEFINES ws-TRAN-BUNDLE-ID PIC X(12)|173|12
ws_bundle_ind_oc2       varchar(1)              30 ws-BUNDLE-IND PIC X(01).|185|1
ws_bill_event_ty_cd_oc3 varchar(4)              30 ws-BILL-EVENT-TY-CD PIC X(04)|186|4
ws_bill_rqst_cd_oc3     varchar(1)              30 ws-BILL-RQST-CD PIC X(01)|190|1
ws_fee_exempt_id_oc3    varchar(1)              30 ws-FEE-EXEMPT-ID PIC X(01)|191|1
ws_fee_exempt_rsn_cd_oc3        varchar(4)              30 ws-FEE-EXEMPT-RSN-CD PIC X(04)|192|4
ws_rule_fee_cd_oc3      varchar(4)              30 ws-RULE-FEE-CD PIC X(04)|196|4
ws_fee_calc_rcl_cd_oc3  varchar(3)              30 ws-FEE-CALC-RCL-CD PIC X(03)|200|3
ws_total_fee_oc3        decimal(18,2)           30 ws-TOTAL-FEE PIC S9(15)V99 COMP-3|203|9
ws_total_int_oc3        decimal(18,5)           30 ws-TOTAL-INT REDEFINES ws-TOTAL-FEE PIC S9(12)V9(05) COMP-3|203|9
ws_pers_fee_oc3         decimal(18,2)           30 ws-PERS-FEE PIC S9(15)V99 COMP-3|212|9
ws_fund_based_acct_chg_oc3      decimal(18,2)           30 ws-FUND-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|212|9
ws_ibd_based_acct_chg_oc3       decimal(18,2)           30 ws-IBD-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|212|9
ws_pers_int_oc3         decimal(18,5)           30 ws-PERS-INT REDEFINES ws-PERS-FEE PIC S9(12)V9(05) COMP-3|212|9
ws_ibd_mark_up_fee_oc3  decimal(18,2)           30 ws-IBD-MARK-UP-FEE PIC S9(15)V99 COMP-3|221|9
ws_ibd_mark_up_int_oc3  decimal(18,5)           30 ws-IBD-MARK-UP-INT REDEFINES ws-IBD-MARK-UP-FEE PIC S9(12)V9(05) COMP-3|221|9
ws_contract_schd_id_oc3 varchar(12)             30 ws-CONTRACT-SCHD-ID PIC X(12)|230|12
ws_ebs_req_ent_id_oc3   varchar(12)             30 ws-EBS-REQ-ENT-ID PIC X(12)|242|12
ws_bill_rule_set_id_oc3 varchar(12)             30 ws-BILL-RULE-SET-ID PIC X(12)|254|12
ws_tran_bundle_id_oc3   varchar(12)             30 ws-TRAN-BUNDLE-ID PIC X(12)|266|12
ws_fxcpt_rule_set_id_oc3        varchar(12)             30 ws-FXCPT-RULE-SET-ID REDEFINES ws-TRAN-BUNDLE-ID PIC X(12)|266|12
ws_bundle_ind_oc3       varchar(1)              30 ws-BUNDLE-IND PIC X(01).|278|1
ws_bill_event_ty_cd_oc4 varchar(4)              30 ws-BILL-EVENT-TY-CD PIC X(04)|279|4
ws_bill_rqst_cd_oc4     varchar(1)              30 ws-BILL-RQST-CD PIC X(01)|283|1
ws_fee_exempt_id_oc4    varchar(1)              30 ws-FEE-EXEMPT-ID PIC X(01)|284|1
ws_fee_exempt_rsn_cd_oc4        varchar(4)              30 ws-FEE-EXEMPT-RSN-CD PIC X(04)|285|4
ws_rule_fee_cd_oc4      varchar(4)              30 ws-RULE-FEE-CD PIC X(04)|289|4
ws_fee_calc_rcl_cd_oc4  varchar(3)              30 ws-FEE-CALC-RCL-CD PIC X(03)|293|3
ws_total_fee_oc4        decimal(18,2)           30 ws-TOTAL-FEE PIC S9(15)V99 COMP-3|296|9
ws_total_int_oc4        decimal(18,5)           30 ws-TOTAL-INT REDEFINES ws-TOTAL-FEE PIC S9(12)V9(05) COMP-3|296|9
ws_pers_fee_oc4         decimal(18,2)           30 ws-PERS-FEE PIC S9(15)V99 COMP-3|305|9
ws_fund_based_acct_chg_oc4      decimal(18,2)           30 ws-FUND-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|305|9
ws_ibd_based_acct_chg_oc4       decimal(18,2)           30 ws-IBD-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|305|9
ws_pers_int_oc4         decimal(18,5)           30 ws-PERS-INT REDEFINES ws-PERS-FEE PIC S9(12)V9(05) COMP-3|305|9
ws_ibd_mark_up_fee_oc4  decimal(18,2)           30 ws-IBD-MARK-UP-FEE PIC S9(15)V99 COMP-3|314|9
ws_ibd_mark_up_int_oc4  decimal(18,5)           30 ws-IBD-MARK-UP-INT REDEFINES ws-IBD-MARK-UP-FEE PIC S9(12)V9(05) COMP-3|314|9
ws_contract_schd_id_oc4 varchar(12)             30 ws-CONTRACT-SCHD-ID PIC X(12)|323|12
ws_ebs_req_ent_id_oc4   varchar(12)             30 ws-EBS-REQ-ENT-ID PIC X(12)|335|12
ws_bill_rule_set_id_oc4 varchar(12)             30 ws-BILL-RULE-SET-ID PIC X(12)|347|12
ws_tran_bundle_id_oc4   varchar(12)             30 ws-TRAN-BUNDLE-ID PIC X(12)|359|12
ws_fxcpt_rule_set_id_oc4        varchar(12)             30 ws-FXCPT-RULE-SET-ID REDEFINES ws-TRAN-BUNDLE-ID PIC X(12)|359|12
ws_bundle_ind_oc4       varchar(1)              30 ws-BUNDLE-IND PIC X(01).|371|1
ws_bill_event_ty_cd_oc5 varchar(4)              30 ws-BILL-EVENT-TY-CD PIC X(04)|372|4
ws_bill_rqst_cd_oc5     varchar(1)              30 ws-BILL-RQST-CD PIC X(01)|376|1
ws_fee_exempt_id_oc5    varchar(1)              30 ws-FEE-EXEMPT-ID PIC X(01)|377|1
ws_fee_exempt_rsn_cd_oc5        varchar(4)              30 ws-FEE-EXEMPT-RSN-CD PIC X(04)|378|4
ws_rule_fee_cd_oc5      varchar(4)              30 ws-RULE-FEE-CD PIC X(04)|382|4
ws_fee_calc_rcl_cd_oc5  varchar(3)              30 ws-FEE-CALC-RCL-CD PIC X(03)|386|3
ws_total_fee_oc5        decimal(18,2)           30 ws-TOTAL-FEE PIC S9(15)V99 COMP-3|389|9
ws_total_int_oc5        decimal(18,5)           30 ws-TOTAL-INT REDEFINES ws-TOTAL-FEE PIC S9(12)V9(05) COMP-3|389|9
ws_pers_fee_oc5         decimal(18,2)           30 ws-PERS-FEE PIC S9(15)V99 COMP-3|398|9
ws_fund_based_acct_chg_oc5      decimal(18,2)           30 ws-FUND-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|398|9
ws_ibd_based_acct_chg_oc5       decimal(18,2)           30 ws-IBD-BASED-ACCT-CHG REDEFINES ws-PERS-FEE PIC S9(15)V99 COMP-3|398|9
ws_pers_int_oc5         decimal(18,5)           30 ws-PERS-INT REDEFINES ws-PERS-FEE PIC S9(12)V9(05) COMP-3|398|9
ws_ibd_mark_up_fee_oc5  decimal(18,2)           30 ws-IBD-MARK-UP-FEE PIC S9(15)V99 COMP-3|407|9
ws_ibd_mark_up_int_oc5  decimal(18,5)           30 ws-IBD-MARK-UP-INT REDEFINES ws-IBD-MARK-UP-FEE PIC S9(12)V9(05) COMP-3|407|9
ws_contract_schd_id_oc5 varchar(12)             30 ws-CONTRACT-SCHD-ID PIC X(12)|416|12
ws_ebs_req_ent_id_oc5   varchar(12)             30 ws-EBS-REQ-ENT-ID PIC X(12)|428|12
ws_bill_rule_set_id_oc5 varchar(12)             30 ws-BILL-RULE-SET-ID PIC X(12)|440|12
ws_tran_bundle_id_oc5   varchar(12)             30 ws-TRAN-BUNDLE-ID PIC X(12)|452|12
ws_fxcpt_rule_set_id_oc5        varchar(12)             30 ws-FXCPT-RULE-SET-ID REDEFINES ws-TRAN-BUNDLE-ID PIC X(12)|452|12
ws_bundle_ind_oc5       varchar(1)              30 ws-BUNDLE-IND PIC X(01).|464|1

**Comment by nayven3** [comment] 2018-01-12 10:13
Send me an email to venkac@gmail.com for quick fix.

**Comment by rbheemana** [comment] 2019-02-01 17:49
@Nandakishore43  Please test with the branch  Issue#51-Field-with-format-S9(11)V99-displays-null-value-in-hive . I have updated the code to handle this.

**Comment by rbheemana** [comment] 2019-02-01 19:59
closing the issue

**Closed as completed by rbheemana** 2019-02-01 19:59 UTC
